import { createFileRoute } from "@tanstack/react-router";
import { useState } from "react";
import { BackToTop, SiteFooter, SiteHeader } from "../components/site-shell";

export const Route=createFileRoute("/")({head:()=>({meta:[{title:"CSTI Brasil | Tecnologia para Comunicação Assertiva"},{name:"description",content:"Estratégia, tecnologia e inteligência para estruturar a comunicação empresarial."},{property:"og:title",content:"CSTI Brasil | Tecnologia para Comunicação Assertiva"},{property:"og:description",content:"Estratégia, tecnologia e inteligência para estruturar a comunicação empresarial."},{property:"og:image",content:"/hero-operacao-csti-v1.png"}]}),component:Home});
const Arrow=()=> <span aria-hidden="true">↗</span>;
const services=[
  {name:"Omnichannel",headline:"Uma operação, mesmo quando a conversa muda de canal.",text:"Centralize canais, equipes e históricos para oferecer continuidade ao atendimento e mais clareza para a gestão.",items:["WhatsApp e canais digitais","Filas e departamentos","Histórico institucional"]},
  {name:"Automação e IA",headline:"Inteligência aplicada a processos reais.",text:"Automatize etapas, desenvolva agentes personalizados e conecte conhecimento, regras e pessoas dentro do fluxo de trabalho.",items:["Agentes de IA personalizados","Automação de jornadas","Projetos sob demanda"]},
  {name:"Integrações",headline:"A comunicação conectada ao restante da empresa.",text:"Integre canais e plataformas aos sistemas que já sustentam sua operação, reduzindo fragmentação e retrabalho.",items:["APIs e sistemas","Dados e contexto","Fluxos integrados"]},
  {name:"Consultoria",headline:"Tecnologia escolhida depois de entender o problema.",text:"Mapeamos processos, ambiente, responsabilidades e objetivos para desenhar uma estrutura coerente e sustentável.",items:["Diagnóstico","Arquitetura","Governança e evolução"]},
];
const markets=["Varejo","Drogarias e Farmácias","Serviços","Saúde","Educação","Empresas","Setor Público"];
function OmnichannelPlatform({mode}:{mode:number}){const item=services[mode];return <div className="solution-system-showcase"><aside><p>{item.name.toUpperCase()}</p><h3>{item.headline}</h3><span>{item.text}</span><ol>{item.items.map((feature,index)=><li key={feature}><small>0{index+1}</small><strong>{feature}</strong></li>)}</ol><a className="button" href={mode===1?"/solucoes/automacao-e-ia":"#contato"}>Explorar solução <Arrow/></a></aside><figure><img src="/plataforma-omnichannel-csti.png" alt="Interface de uma plataforma omnichannel com canais, conversas e contexto do cliente"/><figcaption><span>CSTI ONE · VISÃO DA PLATAFORMA</span><strong>WhatsApp · Instagram · Messenger · Telegram · WebChat · RCS</strong></figcaption></figure></div>}

function Home(){const[active,setActive]=useState(0);return <main id="inicio" className="agency-home">
  <section className="agency-hero"><SiteHeader/><img src="/hero-operacao-csti-v1.png" alt="Equipe trabalhando em uma operação de tecnologia"/><div className="agency-hero-shade"></div><div className="shell agency-hero-content"><p className="agency-kicker">ESTRATÉGIA · TECNOLOGIA · COMUNICAÇÃO</p><h1>Tecnologia para uma comunicação mais assertiva.</h1><p>Estruturamos canais, processos, automações, Inteligência Artificial e integrações para empresas que precisam transformar comunicação em operação.</p><div className="actions"><a className="button" href="#solucoes">Conheça a CSTI <Arrow/></a><a className="agency-link light" href="#contato">Fale com um especialista</a></div></div><div className="hero-caption">CSTI BRASIL<br/><span>TECNOLOGIA PARA COMUNICAÇÃO ASSERTIVA</span></div></section>

  <section className="agency-intro"><div className="shell agency-intro-grid"><p className="agency-index">01 — NOSSO PONTO DE VISTA</p><h2>Comunicação não é apenas um canal.<br/><em>É parte da infraestrutura da empresa.</em></h2><div className="agency-intro-copy"><p>Pessoas, dados, automações e sistemas precisam trabalhar dentro da mesma estratégia. Quando cada elemento opera isoladamente, a tecnologia aumenta a complexidade. Quando existe estrutura, ela cria continuidade.</p><a className="agency-link" href="#solucoes">Entenda nosso ecossistema <Arrow/></a></div></div></section>

  <section className="agency-photo-story"><div className="agency-photo"><img src="/estrategia-csti-v1.png" alt="Equipe analisando uma estratégia de operação"/></div><div className="agency-story"><p className="agency-index">02 — COMO PENSAMOS</p><h2>Antes da plataforma, vem a clareza.</h2><p>Começamos pela realidade da operação: como as conversas chegam, quem precisa agir, quais informações devem acompanhar a jornada e o que precisa estar conectado.</p><ol><li><span>01</span><strong>Entender</strong> contexto, processo e objetivo.</li><li><span>02</span><strong>Estruturar</strong> canais, pessoas e tecnologia.</li><li><span>03</span><strong>Evoluir</strong> com acompanhamento e governança.</li></ol></div></section>

  <section className="agency-services" id="solucoes"><div className="shell"><div className="agency-section-head"><p className="agency-index">03 — SOLUÇÕES</p><h2>Uma operação.<br/>Todos os canais.</h2><p>O sistema aparece primeiro. Ao selecionar uma solução, a coluna apresenta como essa capacidade participa da operação.</p></div><div className="service-editor"><nav aria-label="Soluções CSTI">{services.map((item,i)=><button key={item.name} className={active===i?"active":""} onClick={()=>setActive(i)} aria-pressed={active===i}><span>0{i+1}</span>{item.name}</button>)}</nav><article><OmnichannelPlatform mode={active}/></article></div></div></section>

  <section className="agency-ai"><div className="shell agency-ai-grid"><div><p className="agency-index light-index">04 — AUTOMAÇÃO E INTELIGÊNCIA ARTIFICIAL</p><h2>Projetos com contexto.<br/>Não soluções genéricas.</h2><p>Consultoria, agentes de IA personalizados e automações sob demanda, desenvolvidos conforme o processo, os dados e as regras de cada empresa.</p><a className="button" href="/solucoes/automacao-e-ia">Conheça Automação e IA <Arrow/></a></div><div className="agency-ai-list">{[["Consultoria","Prioridades e arquitetura antes da implementação."],["Agentes personalizados","Conhecimento, regras e limites definidos para a empresa."],["Projetos sob demanda","Automação e integração para desafios específicos."]].map(([t,d],i)=><div key={t}><span>0{i+1}</span><h3>{t}</h3><p>{d}</p></div>)}</div></div></section>

  <section className="agency-segments" id="segmentos"><div className="shell"><div className="agency-section-head segment-heading"><p className="agency-index">05 — SEGMENTOS</p><h2>Tecnologia que entende cada cenário.</h2><p>Partimos da rotina, da linguagem e dos desafios reais de cada mercado.</p><div className="csti-photo-mark" aria-hidden="true"><i></i><b></b></div></div><div className="segment-showcase">{markets.map((market,i)=><a className={`segment-visual segment-visual-${i+1}`} href={market==="Drogarias e Farmácias"?"/segmentos/drogarias-e-farmacias":"/segmentos"} key={market}><span className="segment-number">0{i+1}</span><div><p>{["Varejo","Saúde & varejo","Serviços","Saúde","Educação","Corporativo","Setor público"][i]}</p><strong>{market}</strong><small>{["Jornadas que convertem atendimento em relacionamento.","Do WhatsApp ao balcão, com contexto e continuidade.","Triagem, agenda e especialistas na mesma conversa.","Orientação e retorno em jornadas mais humanas.","Captação, matrícula e relacionamento com alunos.","Canais, departamentos e governança conectados.","Atendimento ao cidadão com rastreabilidade."][i]}</small></div><span className="segment-arrow"><Arrow/></span></a>)}</div><a className="agency-link market-all" href="/segmentos">Explorar todas as soluções por segmento <Arrow/></a></div></section>

  <section className="agency-consulting" id="consultoria"><div className="shell agency-consulting-grid"><div><p className="agency-index">06 — CONSULTORIA</p><h2>Tecnologia sem estratégia é apenas ferramenta.</h2></div><div><p>Analisamos canais, processos, documentação, atendimento e infraestrutura para definir como a tecnologia deve participar da operação.</p><div className="consulting-tags">{["Diagnóstico","Ambiente Meta","WhatsApp Oficial","Processos","Governança","Integrações"].map(x=><span key={x}>{x}</span>)}</div><a className="agency-link" href="#contato">Conheça nossa abordagem <Arrow/></a></div></div></section>

  <section className="agency-close" id="contato"><div className="shell"><p className="agency-index light-index">07 — PRÓXIMO PASSO</p><h2>Sua empresa já se comunica.<br/><em>Nós ajudamos a transformar isso em estrutura.</em></h2><a className="button" href="mailto:contato@cstibrasil.com.br">Fale com um especialista <Arrow/></a></div></section><SiteFooter/><BackToTop/>
  </main>}
