import { createFileRoute } from "@tanstack/react-router";
import { BackToTop, SiteFooter, SiteHeader } from "../components/site-shell";

export const Route=createFileRoute("/rio-de-janeiro")({head:()=>({meta:[{title:"Omnichannel, Automação e IA no Rio de Janeiro | CSTI Brasil"},{name:"description",content:"Soluções omnichannel, WhatsApp Business Platform, automação, Inteligência Artificial e integrações para empresas no Rio de Janeiro e região."},{property:"og:title",content:"Tecnologia para empresas no Rio de Janeiro | CSTI Brasil"},{property:"og:description",content:"Comunicação omnichannel, automação, IA e integrações com atendimento especializado no Rio de Janeiro."},{property:"og:url",content:"https://cstibrasil.com.br/rio-de-janeiro"},{property:"og:image",content:"https://cstibrasil.com.br/og-csti-brasil-oficial.png"}],links:[{rel:"canonical",href:"https://cstibrasil.com.br/rio-de-janeiro"}]}),component:RioDeJaneiroPage});

const Arrow=()=> <span aria-hidden="true">↗</span>;
const phoneHref="tel:+558005208454";
const whatsappHref="https://wa.me/558005208454";

function RioDeJaneiroPage(){return <main id="inicio" className="inner-page local-page"><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify({"@context":"https://schema.org","@type":"Service",name:"Soluções omnichannel, automação e IA no Rio de Janeiro",serviceType:["Comunicação omnichannel","WhatsApp Business Platform","Automação empresarial","Inteligência Artificial personalizada","Integração de sistemas"],provider:{"@id":"https://cstibrasil.com.br/#organization"},areaServed:[{"@type":"City",name:"Rio de Janeiro"},{"@type":"AdministrativeArea",name:"Estado do Rio de Janeiro"}],url:"https://cstibrasil.com.br/rio-de-janeiro",telephone:"0800 520 8454"})}}/><section className="inner-hero local-hero dark"><SiteHeader/><div className="shell local-hero-grid"><div><p className="eyebrow">CSTI BRASIL · RIO DE JANEIRO</p><h1>Tecnologia para empresas que precisam transformar comunicação em <em>operação.</em></h1><p className="lead">Estratégia, plataforma omnichannel, WhatsApp Business, automação, Inteligência Artificial e integrações para operações no Rio de Janeiro e em todo o estado.</p><div className="actions"><a className="button" href={whatsappHref} target="_blank" rel="noreferrer">Fale pelo WhatsApp <Arrow/></a><a className="text-link" href={phoneHref}>0800 520 8454</a></div></div><div className="local-signal" aria-label="Áreas de atuação da CSTI no Rio de Janeiro"><img src="/csti-simbolo-ciano.png" width="592" height="592" alt="Símbolo CSTI Brasil"/><span>RIO DE JANEIRO</span><div><b>Omnichannel</b><b>Automação</b><b>IA aplicada</b><b>Integrações</b></div></div></div></section>
<section className="section local-intro"><div className="shell heading"><p className="eyebrow ink">TECNOLOGIA COM CONTEXTO LOCAL</p><h2>Do atendimento à gestão, uma estrutura conectada.</h2><p>A CSTI ajuda empresas cariocas e fluminenses a organizar canais, equipes, processos e dados em uma operação coerente, mensurável e preparada para evoluir.</p></div><div className="shell local-benefits">{[["01","Centralização de canais","WhatsApp, Instagram, Messenger, Telegram, WebChat e outros canais em uma visão operacional."],["02","Automação com propósito","Fluxos, regras e agentes de IA desenhados conforme a rotina e os objetivos da empresa."],["03","Integrações sob demanda","Conexão com CRM, ERP, APIs, sistemas internos e fontes de dados que já sustentam a operação."]].map(([n,t,d])=><article key={n}><span>{n}</span><h3>{t}</h3><p>{d}</p></article>)}</div></section>
<section className="section dark local-services"><div className="shell"><div className="heading dark-heading"><p className="eyebrow">SOLUÇÕES NO RIO DE JANEIRO</p><h2>Capacidades que trabalham juntas.</h2><p>O projeto pode começar por um canal, processo ou necessidade específica e evoluir para uma estrutura integrada.</p></div><div className="local-service-list">{[["Omnichannel e atendimento","Unifique conversas, filas, departamentos e históricos para preservar o contexto do cliente."],["WhatsApp Business Platform","Estruture o ambiente oficial da Meta com titularidade, governança e capacidade de escala."],["Automação e agentes de IA","Automatize tarefas repetitivas e aplique inteligência com regras, limites e acompanhamento."],["Consultoria e integrações","Mapeie prioridades e conecte a comunicação aos sistemas e processos da empresa."]].map(([t,d],i)=><article key={t}><small>0{i+1}</small><h3>{t}</h3><p>{d}</p></article>)}</div></div></section>
<section className="section local-markets"><div className="shell local-market-grid"><div><p className="eyebrow ink">EMPRESAS E ORGANIZAÇÕES</p><h2>Soluções ajustadas a cada cenário.</h2><p className="body">Atendemos operações que precisam organizar relacionamento, atendimento, distribuição de demandas, automação e continuidade entre o digital e a rotina da empresa.</p></div><div>{["Varejo e redes de lojas","Drogarias e farmácias","Empresas de serviços","Saúde e clínicas","Educação","Operações corporativas","Órgãos e serviços públicos"].map((x,i)=><span key={x}><small>0{i+1}</small>{x}</span>)}</div></div></section>
<section className="agency-close local-contact" id="contato"><div className="shell"><p className="agency-index light-index">ATENDIMENTO · RIO DE JANEIRO</p><h2>Vamos entender sua operação antes de indicar a tecnologia.</h2><div className="actions"><a className="button" href={whatsappHref} target="_blank" rel="noreferrer">Conversar pelo WhatsApp <Arrow/></a><a className="agency-link light" href={phoneHref}>Ligar para 0800 520 8454</a></div></div></section><SiteFooter/><BackToTop/></main>}
