import { createFileRoute } from "@tanstack/react-router";
import { useState } from "react";
import { InfoModal } from "../../components/info-modal";
import { BackToTop, SiteFooter, SiteHeader } from "../../components/site-shell";

export const Route=createFileRoute("/segmentos/drogarias-e-farmacias")({head:()=>({meta:[{title:"Tecnologia para Drogarias e Farmácias | CSTI Brasil"},{name:"description",content:"Comunicação, atendimento e automação conectando canais digitais e a rotina de drogarias e farmácias."}]}),component:DrogariasPage});
const Arrow=()=> <span aria-hidden="true">↗</span>;
const capabilities=[["Atendimento omnichannel","Reúna canais, equipes e histórico para dar continuidade a cada conversa."],["WhatsApp Business Platform","Estruture a operação no ambiente oficial da Meta, com titularidade e escala."],["Filas e departamentos","Direcione cada demanda para a equipe certa, com responsabilidades claras."],["Automação de jornadas","Aplique regras e gatilhos aos pontos repetitivos sem perder o contexto."],["Agentes de IA","Apoie triagem, qualificação e conhecimento com inteligência aplicada."],["Histórico de conversas","Preserve informações importantes para atendimento, gestão e relacionamento."],["Integrações e APIs","Conecte a comunicação aos sistemas que já participam da operação."],["Governança e permissões","Organize acessos, departamentos, documentação e controle operacional."]];
function DrogariasPage(){const[selected,setSelected]=useState<number|null>(null);const capability=selected===null?null:capabilities[selected];return <main id="inicio" className="inner-page pharmacy-page"><section className="inner-hero pharmacy-hero dark"><SiteHeader/><div className="shell inner-hero-grid"><div><p className="eyebrow">CSTI PARA DROGARIAS E FARMÁCIAS</p><h1>Do atendimento digital ao balcão, <em>uma jornada conectada.</em></h1><p className="lead">Tecnologia para organizar conversas, equipes e processos sem perder o contexto entre o WhatsApp e a operação da loja.</p><div className="actions"><a className="button" href="#contato">Fale com um especialista <Arrow/></a><a className="text-link" href="#jornada">Conheça a jornada <span>↓</span></a></div></div><div className="pharmacy-signal" aria-hidden="true"><div className="signal-head"><span>JORNADA / DROGARIA</span><i>OPERAÇÃO CONECTADA</i></div>{["Cliente","WhatsApp","Atendimento","Balcão","Pedido","Histórico"].map((x,i)=><div className="signal-row" key={x}><span>0{i+1}</span><strong>{x}</strong><i></i></div>)}</div></div></section>
  <section className="pharmacy-thesis section"><div className="shell thesis"><div><p className="eyebrow ink">CONTINUIDADE NO ATENDIMENTO</p><h2>O cliente não separa o digital da loja.</h2></div><div className="big-copy"><p>Uma conversa pode começar no WhatsApp, avançar para uma orientação da equipe e terminar no balcão. A operação precisa preservar contexto, responsabilidade e histórico em cada etapa.</p><div className="pharmacy-quote">O canal muda.<br/><strong>A experiência precisa continuar.</strong></div></div></div></section>
  <section className="pain-section section"><div className="shell"><div className="heading"><p className="eyebrow ink">DESAFIOS DA OPERAÇÃO</p><h2>Quando os canais crescem sem estrutura, a equipe perde visão.</h2><p>A tecnologia deve reduzir fragmentação e apoiar o trabalho das pessoas — não criar mais uma camada de complexidade.</p></div><div className="pain-grid">{[["01","Conversas dispersas","Atendimentos em aparelhos e números diferentes dificultam o acompanhamento."],["02","Falta de contexto","O cliente repete informações quando a conversa muda de pessoa ou canal."],["03","Distribuição manual","Demandas chegam sem fila, prioridade ou responsabilidade claramente definida."],["04","Histórico fragmentado","A operação perde continuidade quando registros não permanecem organizados."],["05","Pouca governança","Acesso, titularidade e processos precisam acompanhar o crescimento da equipe."],["06","Integrações isoladas","Canais e sistemas desconectados aumentam retrabalho e reduzem clareza."]].map(([n,t,d])=><article key={n}><span>{n}</span><h3>{t}</h3><p>{d}</p></article>)}</div></div></section>
  <section className="pharmacy-journey section dark" id="jornada"><div className="shell"><div className="heading dark-heading"><p className="eyebrow">JORNADA CONECTADA</p><h2>Uma estrutura para cada conversa <em>avançar.</em></h2><p>O desenho exato depende da realidade da empresa. Este fluxo demonstra como os pontos da operação podem trabalhar de forma coordenada.</p></div><div className="large-journey">{[["01","Entrada","O cliente inicia o contato no canal disponível."],["02","Identificação","A intenção e o contexto orientam o próximo passo."],["03","Distribuição","A conversa segue para a fila ou equipe adequada."],["04","Atendimento","Pessoas, automação e IA apoiam a resolução."],["05","Loja e balcão","A jornada continua na operação física quando necessário."],["06","Histórico","O contexto permanece disponível para relacionamento e gestão."]].map(([n,t,d])=><div key={n}><span>{n}</span><h3>{t}</h3><p>{d}</p><i>→</i></div>)}</div></div></section>
  <section className="pharmacy-capabilities section"><div className="shell"><div className="heading"><p className="eyebrow ink">CAPACIDADES APLICADAS</p><h2>Tecnologia trabalhando dentro da operação.</h2><p>A combinação é definida conforme canais, processos, sistemas e maturidade de cada empresa.</p></div><div className="capability-mosaic">{capabilities.map(([title,description],i)=><button type="button" onClick={()=>setSelected(i)} key={title} className={i===1||i===4?"accent":""}><span>0{i+1}</span><strong>{title}</strong><p>{description}</p><i aria-hidden="true">↗</i></button>)}</div></div></section>
  <section className="pharmacy-governance section"><div className="shell pharmacy-governance-grid"><div><p className="eyebrow ink">ESTRUTURA PROFISSIONAL</p><h2>WhatsApp oficial, processos claros e controle da operação.</h2><p className="body">A CSTI apoia a estruturação do ambiente Meta, da API oficial, das equipes e dos fluxos necessários para uma comunicação empresarial consistente.</p></div><div className="governance-stack">{["Titularidade do ambiente","Usuários e permissões","Departamentos e responsabilidades","Documentação e histórico","Integrações com sistemas","Acompanhamento e evolução"].map((x,i)=><div key={x}><span>0{i+1}</span><strong>{x}</strong></div>)}</div></div></section>
  <section className="final dark" id="contato"><div className="shell"><p className="eyebrow">PRÓXIMO PASSO</p><h2>Sua drogaria já atende pelo digital.<br/><em>Vamos transformar isso em estrutura.</em></h2><a className="button" href="mailto:contato@cstibrasil.com.br">Fale com um especialista <Arrow/></a></div></section><SiteFooter/><BackToTop/>{capability&&<InfoModal open eyebrow="CAPACIDADE PARA DROGARIAS" title={capability[0]} onClose={()=>setSelected(null)} action={<a className="button" href="mailto:contato@cstibrasil.com.br">Aplicar na minha operação <Arrow/></a>}><p>{capability[1]}</p><p>A configuração é dimensionada conforme canais, unidades, equipes, sistemas e regras da drogaria.</p></InfoModal>}</main>}
