import { createFileRoute } from "@tanstack/react-router";
import { useEffect, useState, type FormEvent } from "react";
import type { BlogPost } from "../../lib/blog-server";

export const Route = createFileRoute("/admin/")({ head: () => ({ meta: [{ title: "Editor do Blog | CSTI Brasil" }, { name: "robots", content: "noindex, nofollow" }] }), component: AdminPage });

function AdminPage() {
  const [logged, setLogged] = useState<boolean | null>(null); const [posts, setPosts] = useState<BlogPost[]>([]); const [feedback, setFeedback] = useState("");
  const load = () => fetch("/api/admin-posts").then(async (r) => { if (!r.ok) { setLogged(false); return; } const data = await r.json(); setPosts(data.posts ?? []); setLogged(true); });
  useEffect(() => { void load(); }, []);
  async function login(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setFeedback("Entrando…"); const values = Object.fromEntries(new FormData(event.currentTarget).entries()); const response = await fetch("/api/admin-login", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(values) }); const result = await response.json(); if (!response.ok) return setFeedback(result.error); setFeedback(""); await load(); }
  async function save(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setFeedback("Salvando…"); const values = Object.fromEntries(new FormData(event.currentTarget).entries()); const response = await fetch("/api/admin-posts", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(values) }); const result = await response.json(); if (!response.ok) return setFeedback(result.error); event.currentTarget.reset(); setFeedback("Publicação salva com sucesso."); await load(); }
  if (logged === null) return <main className="admin-page"><p>Carregando painel…</p></main>;
  if (!logged) return <main className="admin-login"><form onSubmit={login}><img src="/csti-logo-oficial-ciano.png" alt="CSTI Brasil"/><span>EDITORIAL CSTI</span><h1>Acesse o painel</h1><label>E-mail<input name="email" type="email" autoComplete="email" required/></label><label>Senha<input name="password" type="password" autoComplete="current-password" required/></label><button className="button">Entrar ↗</button>{feedback && <p>{feedback}</p>}</form></main>;
  return <main className="admin-page"><header><img src="/csti-logo-oficial-ciano.png" alt="CSTI Brasil"/><div><strong>Editor do Blog</strong><a href="/blog" target="_blank">Ver blog ↗</a></div></header><div className="admin-layout"><section className="admin-editor"><p className="eyebrow ink">NOVA PUBLICAÇÃO</p><h1>Criar conteúdo</h1><form onSubmit={save}><label>Título *<input name="title" required/></label><div className="form-row"><label>Categoria<input name="category" defaultValue="Tecnologia"/></label><label>Endereço personalizado<input name="slug" placeholder="gerado pelo título"/></label></div><label>Resumo<input name="excerpt" maxLength={240}/></label><label>Imagem de capa (URL)<input name="cover_url" type="url" placeholder="https://..."/></label><label>Conteúdo *<textarea name="content" rows={14} required placeholder="Escreva o artigo. Separe os parágrafos com uma linha em branco."/></label><div className="form-row"><label>Tags<input name="tags" placeholder="IA, automação, atendimento"/></label><label>Status<select name="status" defaultValue="draft"><option value="draft">Rascunho</option><option value="published">Publicar agora</option></select></label></div><details><summary>Configurações de SEO</summary><label>Título para o Google<input name="seo_title" maxLength={60}/></label><label>Descrição para o Google<textarea name="seo_description" rows={3} maxLength={160}/></label></details><button className="button" type="submit">Salvar publicação ↗</button>{feedback && <p className="admin-feedback">{feedback}</p>}</form></section><aside className="admin-posts"><p className="eyebrow ink">CONTEÚDO</p><h2>Publicações</h2>{posts.length === 0 ? <p>Nenhuma publicação cadastrada.</p> : posts.map((post) => <article key={post.id}><span className={post.status}>{post.status === "published" ? "Publicado" : "Rascunho"}</span><strong>{post.title}</strong><small>Atualizado em {new Intl.DateTimeFormat("pt-BR").format(new Date(post.updated_at))}</small></article>)}</aside></div></main>;
}
