import { createFileRoute } from "@tanstack/react-router";
import { useState } from "react";
import { InfoModal } from "../../components/info-modal";
import { BackToTop, SiteFooter, SiteHeader } from "../../components/site-shell";
export const Route=createFileRoute("/solucoes/automacao-e-ia")({head:()=>({meta:[{title:"Automação e IA Personalizada | CSTI Brasil"},{name:"description",content:"Consultoria, agentes de IA, automações e projetos tecnológicos sob demanda, conectados à realidade da sua operação."}]}),component:AutomationPage});
const Arrow=()=> <span aria-hidden="true">↗</span>;
const services=[
  {n:"01",tag:"ESTRATÉGIA E GOVERNANÇA",title:"Consultoria em automação e Inteligência Artificial",text:"Identificamos onde a automação gera valor, definimos prioridades e desenhamos uma arquitetura coerente com processos, sistemas e objetivos da empresa.",items:["Diagnóstico de processos e oportunidades","Estratégia de IA aplicada ao negócio","Arquitetura, ferramentas e integrações","Governança, acompanhamento e evolução"]},
  {n:"02",tag:"INTELIGÊNCIA COM CONTEXTO",title:"Agentes de IA personalizados",text:"Criamos agentes orientados pelos dados, regras e conhecimento da empresa para apoiar atendimento, qualificação, suporte e rotinas internas.",items:["Base de conhecimento própria","Tom, regras e limites definidos","Integração aos canais da operação","Escalonamento para atendimento humano"]},
  {n:"03",tag:"ENGENHARIA SOB DEMANDA",title:"Projetos de automação com IA",text:"Desenvolvemos fluxos e integrações para desafios específicos, conectando tarefas, informações e sistemas em processos mais consistentes.",items:["Automação de tarefas administrativas","Processamento e organização de dados","Integração entre sistemas e plataformas","Relatórios, alertas e fluxos operacionais"]},
];
const applications=[["Atendimento","Triagem, contexto e apoio à resolução."],["Pré-vendas","Qualificação e organização de oportunidades."],["Suporte interno","Acesso orientado ao conhecimento da empresa."],["Operações","Regras, alertas e tarefas recorrentes."],["Dados","Organização, processamento e síntese de informações."],["Integrações","Troca de dados entre canais e sistemas."],["Relatórios","Consolidação de informações para acompanhamento."],["Jornadas","Ações coordenadas ao longo de um processo."]];
function AutomationPage(){const[selected,setSelected]=useState<number|null>(null);const app=selected===null?null:applications[selected];return <main id="inicio" className="inner-page automation-page"><section className="inner-hero automation-hero dark"><SiteHeader/><div className="shell automation-hero-grid"><div><p className="eyebrow">AUTOMAÇÃO · IA PERSONALIZADA · PROJETOS SOB DEMANDA</p><h1>Inteligência aplicada ao que sua operação <em>realmente precisa.</em></h1><p className="lead">Da identificação da oportunidade à implementação: estratégia, agentes de IA, automações e integrações desenvolvidos com contexto.</p><div className="actions"><a className="button" href="#servicos">Conheça as soluções <Arrow/></a><a className="text-link" href="#contato">Fale sobre seu projeto <Arrow/></a></div></div><div className="automation-canvas" aria-hidden="true"><div className="canvas-head"><span>CSTI / INTELLIGENCE LAYER</span><i>ONLINE</i></div><div className="canvas-core"><b>IA<small>APLICADA</small></b><span className="canvas-node cn-1">Processos</span><span className="canvas-node cn-2">Conhecimento</span><span className="canvas-node cn-3">Sistemas</span><span className="canvas-node cn-4">Pessoas</span></div><div className="canvas-foot"><span>01 DIAGNÓSTICO</span><span>02 PROJETO</span><span>03 EVOLUÇÃO</span></div></div></div></section>
<section className="automation-position section"><div className="shell position-grid"><div><p className="eyebrow ink">ANTES DE AUTOMATIZAR</p><h2>O processo precisa fazer sentido.</h2></div><div><p>Automação não começa pela escolha de uma ferramenta. Começa pela compreensão do processo, das pessoas envolvidas, dos dados disponíveis e do resultado esperado.</p><strong>Estratégia primeiro.<br/>Tecnologia com propósito.</strong></div></div></section>
<section className="automation-services section" id="servicos"><div className="shell"><div className="heading"><p className="eyebrow ink">COMO A CSTI ATUA</p><h2>Três frentes.<br/><em>Uma visão integrada.</em></h2><p>Projetos construídos para a realidade da empresa e preparados para evoluir com a operação.</p></div><div className="service-stories">{services.map((s,i)=><article key={s.n} className={`service-story story-${i+1}`}><div className="story-number"><span>{s.n}</span><small>{s.tag}</small></div><div className="story-copy"><h2>{s.title}</h2><p>{s.text}</p><a href="#contato">Conversar sobre esta solução <Arrow/></a></div><div className="story-list">{s.items.map((item,j)=><div key={item}><span>0{j+1}</span><strong>{item}</strong></div>)}</div></article>)}</div></div></section>
<section className="automation-apps section dark"><div className="shell"><div className="heading dark-heading"><p className="eyebrow">APLICAÇÕES POSSÍVEIS</p><h2>IA e automação dentro do <em>fluxo de trabalho.</em></h2><p>Os casos de uso são definidos após o diagnóstico. Estas são frentes em que a tecnologia pode apoiar operações reais.</p></div><div className="application-cloud">{applications.map(([t,d],i)=><button type="button" onClick={()=>setSelected(i)} key={t} className={`app-card app-${i+1}`}><span>0{i+1}</span><h3>{t}</h3><p>{d}</p><small>Ver aplicação ↗</small></button>)}</div></div></section>
<section className="custom-project section"><div className="shell custom-grid"><div className="custom-visual" aria-hidden="true"><div className="custom-orbit"><b>CSTI<small>PROJETO</small></b>{["Objetivo","Dados","Fluxo","Integração"].map((x,i)=><span className={`custom-node custom-${i+1}`} key={x}>{x}</span>)}</div></div><div><p className="eyebrow ink">PROJETOS SOB DEMANDA</p><h2>Nem todo desafio cabe em uma solução pronta.</h2><p className="body">Quando a necessidade exige uma abordagem específica, reunimos análise, automação, IA e integração para construir uma solução alinhada ao ambiente da empresa.</p><div className="custom-principles"><span><small>01</small><strong>Escopo claro</strong><p>Problema, objetivo e critérios definidos antes da execução.</p></span><span><small>02</small><strong>Arquitetura adequada</strong><p>Tecnologia escolhida conforme contexto e integração.</p></span><span><small>03</small><strong>Evolução responsável</strong><p>Acompanhamento para ajustar e ampliar o projeto.</p></span></div></div></div></section>
<section className="automation-method section"><div className="shell"><div className="heading"><p className="eyebrow ink">DA IDEIA À OPERAÇÃO</p><h2>Um processo claro para reduzir incerteza.</h2><p>Cada etapa produz entendimento e orienta a decisão seguinte.</p></div><div className="automation-steps">{[["01","Descoberta","Entendimento do cenário, processo e objetivo."],["02","Diagnóstico","Mapeamento de oportunidades, dados e restrições."],["03","Arquitetura","Definição do fluxo, integrações e responsabilidades."],["04","Implementação","Construção, configuração e validação da solução."],["05","Operação","Entrada controlada no ambiente de trabalho."],["06","Evolução","Acompanhamento, aprendizado e melhorias."]].map(([n,t,d])=><div key={n}><span>{n}</span><h3>{t}</h3><p>{d}</p></div>)}</div></div></section>
<section className="final dark" id="contato"><div className="shell"><p className="eyebrow">FALE SOBRE SEU PROJETO</p><h2>Existe um processo que sua empresa precisa <em>organizar, integrar ou automatizar?</em></h2><a className="button" href="mailto:contato@cstibrasil.com.br">Converse com um especialista <Arrow/></a></div></section><SiteFooter/><BackToTop/>{app&&<InfoModal open eyebrow="APLICAÇÃO DE AUTOMAÇÃO E IA" title={app[0]} onClose={()=>setSelected(null)} action={<a className="button" href="mailto:contato@cstibrasil.com.br">Conversar sobre aplicação <Arrow/></a>}><p>{app[1]}</p><p>A implementação é definida após entender processo, dados, integrações, responsáveis e resultado esperado.</p></InfoModal>}</main>}
