/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SegmentosIndexRouteImport } from './routes/segmentos/index'
import { Route as SegmentosDrogariasEFarmaciasRouteImport } from './routes/segmentos/drogarias-e-farmacias'
import { Route as SolucoesAutomacaoEIaRouteImport } from './routes/solucoes/automacao-e-ia'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SegmentosIndexRoute = SegmentosIndexRouteImport.update({
  id: '/segmentos/',
  path: '/segmentos/',
  getParentRoute: () => rootRouteImport,
} as any)
const SegmentosDrogariasEFarmaciasRoute =
  SegmentosDrogariasEFarmaciasRouteImport.update({
    id: '/segmentos/drogarias-e-farmacias',
    path: '/segmentos/drogarias-e-farmacias',
    getParentRoute: () => rootRouteImport,
  } as any)
const SolucoesAutomacaoEIaRoute = SolucoesAutomacaoEIaRouteImport.update({
  id: '/solucoes/automacao-e-ia',
  path: '/solucoes/automacao-e-ia',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/segmentos/drogarias-e-farmacias': typeof SegmentosDrogariasEFarmaciasRoute
  '/solucoes/automacao-e-ia': typeof SolucoesAutomacaoEIaRoute
  '/segmentos/': typeof SegmentosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/segmentos/drogarias-e-farmacias': typeof SegmentosDrogariasEFarmaciasRoute
  '/solucoes/automacao-e-ia': typeof SolucoesAutomacaoEIaRoute
  '/segmentos': typeof SegmentosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/segmentos/drogarias-e-farmacias': typeof SegmentosDrogariasEFarmaciasRoute
  '/solucoes/automacao-e-ia': typeof SolucoesAutomacaoEIaRoute
  '/segmentos/': typeof SegmentosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/segmentos/drogarias-e-farmacias'
    | '/solucoes/automacao-e-ia'
    | '/segmentos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/segmentos/drogarias-e-farmacias'
    | '/solucoes/automacao-e-ia'
    | '/segmentos'
  id:
    | '__root__'
    | '/'
    | '/segmentos/drogarias-e-farmacias'
    | '/solucoes/automacao-e-ia'
    | '/segmentos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SegmentosDrogariasEFarmaciasRoute: typeof SegmentosDrogariasEFarmaciasRoute
  SolucoesAutomacaoEIaRoute: typeof SolucoesAutomacaoEIaRoute
  SegmentosIndexRoute: typeof SegmentosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/segmentos/': {
      id: '/segmentos/'
      path: '/segmentos'
      fullPath: '/segmentos/'
      preLoaderRoute: typeof SegmentosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/segmentos/drogarias-e-farmacias': {
      id: '/segmentos/drogarias-e-farmacias'
      path: '/segmentos/drogarias-e-farmacias'
      fullPath: '/segmentos/drogarias-e-farmacias'
      preLoaderRoute: typeof SegmentosDrogariasEFarmaciasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solucoes/automacao-e-ia': {
      id: '/solucoes/automacao-e-ia'
      path: '/solucoes/automacao-e-ia'
      fullPath: '/solucoes/automacao-e-ia'
      preLoaderRoute: typeof SolucoesAutomacaoEIaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SegmentosDrogariasEFarmaciasRoute: SegmentosDrogariasEFarmaciasRoute,
  SolucoesAutomacaoEIaRoute: SolucoesAutomacaoEIaRoute,
  SegmentosIndexRoute: SegmentosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
